name: Problems
on: workflow_dispatch
jobs:
  problems:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python ytplaylists.py problems "Volleyball Dirty" "6" >> $GITHUB_STEP_SUMMARY
        env:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          expires_at: ${{ secrets.EXPIRES_AT }}
          expires_in: ${{ secrets.EXPIRES_IN }}
